ARDUINO_DIR = /usr/share/arduino
# the following shell commands extract the path to ../sketches/libaries
# http://www.gnu.org/software/make/manual/html_node/File-Name-Functions.html
ARDUINO_SKETCHBOOK = $(realpath $(dir $(shell pwd)))
BOARD_TAG    = uno
ARDUINO_LIBS = SoftwareSerial
include /usr/share/arduino/Arduino.mk
