ARDUINO_DIR = /usr/share/arduino
# the following shell commands extract the path to ../sketches/libaries
# not very robust pathname output is given as sketches//libraries)
ARDUINO_SKETCHBOOK = $(dir $(shell pwd))
BOARD_TAG    = uno
ARDUINO_LIBS =
include /usr/share/arduino/Arduino.mk